# Define variables
PANDOC = pandoc
INPUT = paper/paper.md
OUTPUT = Assignment_3.pdf
PDF_ENGINE = xelatex
TEMPLATE = tex/mytemplate.tex
OUT_DIR = build
PDF_DIR = pdf
BIB_FILE = bib/references.bib
TEX_FILE = $(OUT_DIR)/$(OUTPUT:.pdf=.tex)

# Ensure the output and pdf directories exist
$(shell mkdir -p $(OUT_DIR) $(PDF_DIR))

all: $(PDF_DIR)/$(OUTPUT)

# Step to generate TeX from Markdown
$(TEX_FILE): $(INPUT) $(TEMPLATE) $(BIB_FILE)
	$(PANDOC) $(INPUT) -o $(TEX_FILE) --template=$(TEMPLATE) --pdf-engine=$(PDF_ENGINE)

# Step to process bibliography and finalize PDF
$(PDF_DIR)/$(OUTPUT): $(TEX_FILE)
	$(PDF_ENGINE) -output-directory=$(OUT_DIR) $(TEX_FILE) # First xelatex run
	biber $(basename $(TEX_FILE)) # Run biber on the .bcf file generated by xelatex
	$(PDF_ENGINE) -output-directory=$(OUT_DIR) $(TEX_FILE) # Second xelatex run
	$(PDF_ENGINE) -output-directory=$(OUT_DIR) $(TEX_FILE) # Third xelatex run for final adjustments
	mv $(OUT_DIR)/$(OUTPUT) $(PDF_DIR)

clean:
	rm -rf $(OUT_DIR) $(PDF_DIR)/$(OUTPUT)

open: $(PDF_DIR)/$(OUTPUT)
	open $(PDF_DIR)/$(OUTPUT)

re: clean all

.PHONY: all clean open re

